export interface Product {
  name: string;
  slug: string;
  cas: string;
  category: string;
  image: string;
  formula: string;
  apps: string[];
  desc: string;
  purity: string;
  packaging: string;
  appearance: string;
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  desc: string;
  image: string;
}

export const categories: Category[] = [
  { id: "industrial-chemicals", name: "Industrial Chemicals", icon: "🏭", desc: "Core industrial raw materials including acids, bases, solvents, and intermediates for manufacturing processes.", image: "/images/industrial/hydrochloric-acid.webp" },
  { id: "agricultural-chemicals", name: "Agricultural & Fertilizer Chemicals", icon: "🌾", desc: "Fertilizers, herbicides, and crop protection chemicals for modern agriculture and soil management.", image: "/images/agricultural/urea.webp" },
  { id: "food-feed-additives", name: "Food & Feed Additives", icon: "🍽️", desc: "Preservatives, thickeners, sweeteners, acidulants, and nutritional supplements for food and animal feed.", image: "/images/food-feed/citric-acid.webp" },
  { id: "water-treatment", name: "Water Treatment Chemicals", icon: "💧", desc: "Disinfectants, coagulants, flocculants, and corrosion inhibitors for water and wastewater treatment.", image: "/images/water-treatment/calcium-hypochlorite.jpg" },
  { id: "mining-chemicals", name: "Mining & Mineral Processing", icon: "⛏️", desc: "Flotation reagents, extraction chemicals, and processing aids for gold, copper, zinc, and base metal mining.", image: "/images/mining/activated-carbon.jpg" },
  { id: "pharma-chemicals", name: "Pharmaceutical & Lab Chemicals", icon: "💊", desc: "High-purity chemicals, excipients, and active ingredients for pharmaceutical and laboratory applications.", image: "/images/pharma/ethanol.webp" },
  { id: "inorganic-chemicals", name: "Inorganic Chemicals & Metals", icon: "⚗️", desc: "Metal compounds, oxides, and inorganic salts for specialized industrial and technology applications.", image: "/images/inorganic/copper-oxide.webp" },
  { id: "solvents-glycols", name: "Solvents & Glycols", icon: "🧪", desc: "Organic solvents, glycol ethers, and specialty fluids for coatings, cleaning, and chemical processing.", image: "/images/solvents/butanol.webp" },
  { id: "paper-pulp-textile", name: "Paper, Pulp & Textile Chemicals", icon: "📄", desc: "Sizing agents, coating chemicals, and processing aids for paper, pulp, and textile manufacturing.", image: "/images/food-feed/methyl-cellulose.webp" },
  { id: "rubber-leather-specialty", name: "Rubber, Leather & Specialty", icon: "🔧", desc: "Processing aids, tanning agents, and specialty chemicals for rubber, leather, and niche industrial applications.", image: "/images/rubber-specialty/oleic-acid.webp" },
];

export const products: Product[] = [
  // INDUSTRIAL CHEMICALS
  { name: "Hydrochloric Acid", slug: "hydrochloric-acid", cas: "7647-01-0", category: "industrial-chemicals", image: "/images/industrial/hydrochloric-acid.webp", formula: "HCl", apps: ["Metal Processing", "pH Control", "Oil Well Acidizing", "Food Processing"], desc: "A strong mineral acid widely used in industrial processing, steel pickling, and pH regulation. Available in various concentrations for diverse applications.", purity: "30-37%", packaging: "IBC, Tanker, Drums", appearance: "Clear colorless liquid" },
  { name: "Caustic Soda Flakes", slug: "caustic-soda-flakes", cas: "1310-73-2", category: "industrial-chemicals", image: "/images/industrial/caustic-soda-flakes.webp", formula: "NaOH", apps: ["Pulp & Paper", "Soap Manufacturing", "Water Treatment", "Chemical Synthesis"], desc: "High-purity sodium hydroxide flakes essential for chemical manufacturing, water treatment, and the production of soaps, detergents, and paper pulp.", purity: "98-99%", packaging: "25kg Bags, Bulk", appearance: "White flakes" },
  { name: "Sulfuric Acid", slug: "sulfuric-acid", cas: "7664-93-9", category: "industrial-chemicals", image: "/images/industrial/sulfuric-acid.webp", formula: "H2SO4", apps: ["Fertilizer Production", "Metal Processing", "Chemical Manufacturing", "Battery Acid"], desc: "One of the most widely produced industrial chemicals, critical for fertilizer manufacturing, petroleum refining, and chemical synthesis processes.", purity: "93-98%", packaging: "IBC, Tanker", appearance: "Clear oily liquid" },
  { name: "Adipic Acid", slug: "adipic-acid", cas: "124-04-9", category: "industrial-chemicals", image: "/images/industrial/adipic-acid.webp", formula: "C6H10O4", apps: ["Nylon Production", "Plasticizers", "Food Additive", "Polyurethanes"], desc: "A key building block in nylon 6,6 production and a versatile intermediate for plasticizers, coatings, and specialty polyurethane applications.", purity: "99.7%", packaging: "25kg Bags", appearance: "White crystalline powder" },
  { name: "Ethyl Acetate", slug: "ethyl-acetate", cas: "141-78-6", category: "industrial-chemicals", image: "/images/industrial/ethyl-acetate.webp", formula: "C4H8O2", apps: ["Coatings", "Adhesives", "Printing Inks", "Pharmaceutical Extraction"], desc: "A widely used organic solvent prized for its low toxicity and pleasant odor. Essential in coating formulations, adhesive manufacturing, and pharmaceutical processing.", purity: "99.5%", packaging: "Drums, IBC", appearance: "Clear colorless liquid" },
  { name: "PVC Resins", slug: "pvc-resins", cas: "9002-86-2", category: "industrial-chemicals", image: "/images/industrial/pvc-resins.webp", formula: "(C2H3Cl)n", apps: ["Pipes & Fittings", "Wire Insulation", "Packaging", "Construction"], desc: "Versatile polyvinyl chloride resins for extrusion and injection molding applications in construction, electrical insulation, and packaging industries.", purity: "K-value 57-72", packaging: "25kg Bags, Bulk", appearance: "White powder" },
  { name: "Monoethylene Glycol", slug: "monoethylene-glycol", cas: "107-21-1", category: "industrial-chemicals", image: "/images/industrial/titanium-dioxide.webp", formula: "C2H6O2", apps: ["Antifreeze", "Polyester Fiber", "PET Bottles", "Coolants"], desc: "An essential raw material for polyester fiber and PET resin production, also widely used as an antifreeze and coolant in automotive and HVAC systems.", purity: "99.5%", packaging: "Drums, Flexitanks", appearance: "Clear colorless liquid" },
  { name: "Linear Alkyl Benzene Sulfonic Acid", slug: "labsa", cas: "27176-87-0", category: "industrial-chemicals", image: "/images/industrial/linear-alkyl-benzene.webp", formula: "C18H30O3S", apps: ["Detergents", "Cleaning Products", "Emulsifiers", "Textile Processing"], desc: "The primary surfactant used in the formulation of household and industrial detergents, offering excellent cleaning performance and biodegradability.", purity: "96%", packaging: "Drums, IBC", appearance: "Brown viscous liquid" },
  { name: "Oxalic Acid", slug: "oxalic-acid", cas: "144-62-7", category: "industrial-chemicals", image: "/images/industrial/oxalic-acid.webp", formula: "C2H2O4", apps: ["Metal Cleaning", "Bleaching", "Rust Removal", "Textile Processing"], desc: "A powerful reducing agent used in metal surface treatment, rust removal, bleaching operations, and as an analytical reagent in laboratory settings.", purity: "99.6%", packaging: "25kg Bags", appearance: "White crystalline powder" },
  { name: "Paraformaldehyde", slug: "paraformaldehyde", cas: "30525-89-4", category: "industrial-chemicals", image: "/images/industrial/paraformaldehyde.webp", formula: "(CH2O)n", apps: ["Resins", "Disinfection", "Herbicide Synthesis", "Adhesives"], desc: "A polymerized form of formaldehyde used in resin manufacturing, fumigation, and as an intermediate in herbicide and pharmaceutical production.", purity: "91-96%", packaging: "25kg Bags", appearance: "White powder/flakes" },
  { name: "Zinc Sulphate Granular", slug: "zinc-sulphate-granular", cas: "7733-02-0", category: "industrial-chemicals", image: "/images/industrial/zinc-sulphate.jpg", formula: "ZnSO4", apps: ["Fertilizers", "Animal Feed", "Water Treatment", "Electroplating"], desc: "A versatile zinc compound used as a micronutrient in agriculture, a dietary supplement in animal feed, and in electroplating and water treatment applications.", purity: "98%", packaging: "25kg Bags", appearance: "White granules" },
  { name: "Zinc Chloride", slug: "zinc-chloride", cas: "7646-85-7", category: "industrial-chemicals", image: "/images/industrial/zinc-chloride.jpg", formula: "ZnCl2", apps: ["Soldering Flux", "Textile Processing", "Chemical Synthesis", "Wood Preservation"], desc: "A highly soluble zinc salt used as a soldering flux, textile processing agent, and catalyst in organic synthesis. Also applied in wood preservation treatments.", purity: "98%", packaging: "25kg Bags, Drums", appearance: "White granular powder" },
  { name: "Sodium Lauryl Ether Sulfate", slug: "sles", cas: "9004-82-4", category: "industrial-chemicals", image: "/images/industrial/sodium-lauryl-ether-sulfate.webp", formula: "C12H25NaO4S", apps: ["Personal Care", "Detergents", "Shampoos", "Cleaning Products"], desc: "A widely used anionic surfactant that provides excellent foaming and cleaning properties for personal care products, household cleaners, and industrial detergents.", purity: "70%", packaging: "Drums, IBC", appearance: "Clear viscous liquid" },

  // AGRICULTURAL & FERTILIZER CHEMICALS
  { name: "Ammonium Sulphate", slug: "ammonium-sulphate", cas: "7783-20-2", category: "agricultural-chemicals", image: "/images/agricultural/ammonium-sulfate.webp", formula: "(NH4)2SO4", apps: ["Nitrogen Fertilizer", "Soil Amendment", "Food Additive", "Flame Retardant"], desc: "A reliable nitrogen and sulfur fertilizer that promotes vigorous crop growth and helps acidify alkaline soils for optimal nutrient absorption.", purity: "21% N, 24% S", packaging: "50kg Bags, Bulk", appearance: "White crystalline granules" },
  { name: "Potassium Chloride", slug: "potassium-chloride", cas: "7447-40-7", category: "agricultural-chemicals", image: "/images/agricultural/potassium-chloride.webp", formula: "KCl", apps: ["Potash Fertilizer", "Food Processing", "Pharmaceutical", "Water Softening"], desc: "The world's most common potassium fertilizer, supplying essential potassium for crop yield improvement and quality enhancement across all agricultural systems.", purity: "60% K2O", packaging: "50kg Bags, Bulk", appearance: "White/red crystalline" },
  { name: "Urea", slug: "urea", cas: "57-13-6", category: "agricultural-chemicals", image: "/images/agricultural/urea.webp", formula: "CO(NH2)2", apps: ["Nitrogen Fertilizer", "Animal Feed", "Resin Production", "SCR Systems"], desc: "The most widely used solid nitrogen fertilizer in the world, delivering 46% nitrogen content for efficient crop nutrition. Also used in urea-formaldehyde resins and diesel exhaust fluid.", purity: "46% N", packaging: "50kg Bags, Bulk", appearance: "White prilled/granular" },
  { name: "NPK Fertilizer", slug: "npk-fertilizer", cas: "Mixed", category: "agricultural-chemicals", image: "/images/agricultural/npk-fertilizer.jpg", formula: "N-P-K", apps: ["Crop Nutrition", "Horticulture", "Turf Management", "Hydroponics"], desc: "Compound fertilizer blending nitrogen, phosphorus, and potassium in balanced ratios tailored to specific crop needs. Available in multiple formulations for diverse agricultural applications.", purity: "Various ratios", packaging: "50kg Bags, Bulk", appearance: "Granules" },
  { name: "Glyphosate", slug: "glyphosate", cas: "1071-83-6", category: "agricultural-chemicals", image: "/images/agricultural/glyphosate.jpg", formula: "C3H8NO5P", apps: ["Herbicide", "Weed Control", "Crop Desiccation", "Land Management"], desc: "A broad-spectrum systemic herbicide used to control weeds in agricultural, forestry, and land management applications. Available in various formulation strengths.", purity: "95% TC", packaging: "Drums, IBC", appearance: "White crystalline powder" },
  { name: "Diammonium Phosphate", slug: "diammonium-phosphate", cas: "7783-28-0", category: "agricultural-chemicals", image: "/images/agricultural/diammonium-phosphate.jpg", formula: "(NH4)2HPO4", apps: ["Starter Fertilizer", "Phosphorus Source", "Fire Retardant", "Yeast Nutrient"], desc: "A high-analysis phosphorus fertilizer containing both nitrogen and phosphorus, ideal as a starter fertilizer and for correcting phosphorus deficiencies in soil.", purity: "18-46-0", packaging: "50kg Bags, Bulk", appearance: "Dark granules" },
  { name: "Ammonium Nitrate", slug: "ammonium-nitrate", cas: "6484-52-2", category: "agricultural-chemicals", image: "/images/agricultural/ammonium-nitrate.jpg", formula: "NH4NO3", apps: ["Nitrogen Fertilizer", "Instant Cold Packs", "Mining Explosives"], desc: "A high-nitrogen fertilizer providing both ammonium and nitrate nitrogen forms for immediate and sustained crop nutrition across all growing conditions.", purity: "34.5% N", packaging: "50kg Bags", appearance: "White prills" },
  { name: "Calcium Nitrate", slug: "calcium-nitrate", cas: "10124-37-5", category: "agricultural-chemicals", image: "/images/agricultural/calcium-nitrate.webp", formula: "Ca(NO3)2", apps: ["Fertigation", "Greenhouse Crops", "Concrete Additive", "Wastewater Treatment"], desc: "A highly soluble calcium and nitrogen source ideal for drip irrigation and foliar application, providing readily available nutrients for high-value crops.", purity: "15.5% N, 19% Ca", packaging: "25kg Bags", appearance: "White granules" },
  { name: "Potassium Nitrate", slug: "potassium-nitrate", cas: "7757-79-1", category: "agricultural-chemicals", image: "/images/agricultural/potassium-nitrate.webp", formula: "KNO3", apps: ["Specialty Fertilizer", "Hydroponics", "Food Preservation", "Glass Manufacturing"], desc: "A chloride-free potassium and nitrogen fertilizer prized in precision agriculture, hydroponics, and greenhouse cultivation for sensitive high-value crops.", purity: "13-0-46", packaging: "25kg Bags", appearance: "White crystalline" },
  { name: "Magnesium Sulphate", slug: "magnesium-sulphate", cas: "7487-88-9", category: "agricultural-chemicals", image: "/images/agricultural/magnesium-sulphate.webp", formula: "MgSO4", apps: ["Foliar Feed", "Soil Amendment", "Bath Salts", "Pharmaceutical"], desc: "An essential magnesium and sulfur source for correcting deficiencies in crops, especially in magnesium-demanding plants like tomatoes, peppers, and roses.", purity: "99.5%", packaging: "25kg Bags", appearance: "White crystalline" },
  { name: "Calcium Oxide", slug: "calcium-oxide", cas: "1305-78-8", category: "agricultural-chemicals", image: "/images/agricultural/calcium-oxide.webp", formula: "CaO", apps: ["Soil Liming", "Construction", "Steel Making", "Water Treatment"], desc: "Quicklime used for soil pH correction, as a desiccant, and in construction materials. Provides rapid alkalinity adjustment in agricultural and industrial processes.", purity: "90-95%", packaging: "25kg Bags, Bulk", appearance: "White powder/lumps" },
  { name: "Formic Acid", slug: "formic-acid", cas: "64-18-6", category: "agricultural-chemicals", image: "/images/agricultural/formic-acid.webp", formula: "CH2O2", apps: ["Silage Preservation", "Leather Tanning", "Textile Dyeing", "Antibacterial Agent"], desc: "A naturally occurring organic acid used in silage preservation, animal feed acidification, and as an antibacterial agent in livestock farming.", purity: "85-99%", packaging: "Drums, IBC", appearance: "Clear colorless liquid" },
  { name: "Sulfur", slug: "sulfur", cas: "7704-34-9", category: "agricultural-chemicals", image: "/images/agricultural/sulfur.webp", formula: "S", apps: ["Fungicide", "Soil Amendment", "Vulcanization", "Chemical Synthesis"], desc: "An essential agricultural input used as a fungicide, soil acidifier, and sulfur nutrient source. Also critical in rubber vulcanization and sulfuric acid production.", purity: "99.5-99.9%", packaging: "Bags, Bulk", appearance: "Yellow granules/powder" },

  // FOOD & FEED ADDITIVES
  { name: "Citric Acid", slug: "citric-acid", cas: "77-92-9", category: "food-feed-additives", image: "/images/food-feed/citric-acid.webp", formula: "C6H8O7", apps: ["Acidulant", "Preservative", "Flavor Enhancer", "Chelating Agent"], desc: "The most widely used organic acid in food and beverage manufacturing, providing tartness, pH control, and antioxidant properties. Available in anhydrous and monohydrate forms.", purity: "99.5%", packaging: "25kg Bags", appearance: "White crystalline" },
  { name: "Ascorbic Acid", slug: "ascorbic-acid", cas: "50-81-7", category: "food-feed-additives", image: "/images/food-feed/ascorbic-acid.webp", formula: "C6H8O6", apps: ["Vitamin C Supplement", "Antioxidant", "Bread Improver", "Meat Curing"], desc: "Vitamin C in its purest form, used as a nutritional fortifier, antioxidant, and dough improver. Essential in pharmaceutical formulations and food preservation.", purity: "99%", packaging: "25kg Drums", appearance: "White crystalline powder" },
  { name: "Xanthan Gum", slug: "xanthan-gum", cas: "11138-66-2", category: "food-feed-additives", image: "/images/food-feed/xanthan-gum.webp", formula: "Polysaccharide", apps: ["Thickener", "Stabilizer", "Emulsifier", "Gluten-Free Baking"], desc: "A powerful polysaccharide thickener and stabilizer used in food, cosmetics, and industrial drilling fluids. Provides excellent viscosity control at low concentrations.", purity: "Food Grade", packaging: "25kg Bags", appearance: "Off-white powder" },
  { name: "Sodium Benzoate", slug: "sodium-benzoate", cas: "532-32-1", category: "food-feed-additives", image: "/images/food-feed/sodium-benzoate.webp", formula: "C7H5NaO2", apps: ["Preservative", "Beverages", "Cosmetics", "Pharmaceuticals"], desc: "A widely approved antimicrobial preservative effective against yeasts, molds, and bacteria in acidic food products, beverages, and personal care formulations.", purity: "99%", packaging: "25kg Bags", appearance: "White granular powder" },
  { name: "Sorbic Acid", slug: "sorbic-acid", cas: "110-44-1", category: "food-feed-additives", image: "/images/food-feed/sorbic-acid.webp", formula: "C6H8O2", apps: ["Food Preservative", "Wine Making", "Cosmetics", "Animal Feed"], desc: "A naturally derived preservative that inhibits mold and yeast growth in cheese, baked goods, wine, and personal care products without affecting taste or odor.", purity: "99%", packaging: "25kg Bags", appearance: "White crystalline powder" },
  { name: "Potassium Sorbate", slug: "potassium-sorbate", cas: "24634-61-5", category: "food-feed-additives", image: "/images/food-feed/potassium-sorbate.webp", formula: "C6H7KO2", apps: ["Beverages", "Dairy Products", "Baked Goods", "Personal Care"], desc: "The water-soluble salt of sorbic acid, preferred for liquid applications. A highly effective preservative approved for use in foods, beverages, and cosmetics worldwide.", purity: "99%", packaging: "25kg Bags", appearance: "White granules" },
  { name: "Agar Agar", slug: "agar-agar", cas: "9002-18-0", category: "food-feed-additives", image: "/images/food-feed/agar-agar.webp", formula: "Polysaccharide", apps: ["Gelling Agent", "Vegan Gelatin", "Microbiological Media", "Confectionery"], desc: "A plant-based gelling agent derived from seaweed, used as a vegetarian gelatin substitute in confectionery, dairy desserts, and microbiological culture media.", purity: "Food Grade", packaging: "25kg Bags", appearance: "White powder/strips" },
  { name: "Dextrose", slug: "dextrose", cas: "50-99-7", category: "food-feed-additives", image: "/images/food-feed/dextrose.webp", formula: "C6H12O6", apps: ["Sweetener", "Fermentation", "IV Solutions", "Baking"], desc: "A naturally occurring simple sugar used as a sweetener, fermentation substrate, and energy source in food, pharmaceutical, and brewing applications.", purity: "99.5%", packaging: "25kg Bags", appearance: "White crystalline powder" },
  { name: "Maltodextrine", slug: "maltodextrine", cas: "9050-36-6", category: "food-feed-additives", image: "/images/food-feed/maltodextrine.webp", formula: "Polysaccharide", apps: ["Carrier Agent", "Thickener", "Sports Nutrition", "Encapsulation"], desc: "A versatile carbohydrate used as a bulking agent, spray-drying carrier, and energy source in sports nutrition, instant beverages, and seasoning blends.", purity: "DE 10-20", packaging: "25kg Bags", appearance: "White powder" },
  { name: "Guar Gum", slug: "guar-gum", cas: "9000-30-0", category: "food-feed-additives", image: "/images/food-feed/guar-gum.webp", formula: "Polysaccharide", apps: ["Thickener", "Ice Cream", "Gluten-Free", "Oil Drilling"], desc: "A natural galactomannan gum providing viscosity and binding properties in ice cream, baked goods, sauces, and industrial applications including hydraulic fracturing.", purity: "Food Grade", packaging: "25kg Bags", appearance: "Off-white powder" },
  { name: "Lactic Acid", slug: "lactic-acid", cas: "50-21-5", category: "food-feed-additives", image: "/images/food-feed/lactic-acid.webp", formula: "C3H6O3", apps: ["Acidulant", "Preservative", "Bioplastics", "Skin Care"], desc: "A naturally occurring organic acid used for pH adjustment, flavor enhancement, and preservation in food products. Also a key monomer for biodegradable PLA plastics.", purity: "80-88%", packaging: "Drums, IBC", appearance: "Clear colorless liquid" },
  { name: "Monosodium Glutamate", slug: "monosodium-glutamate", cas: "142-47-2", category: "food-feed-additives", image: "/images/food-feed/monosodium-glutamate.webp", formula: "C5H8NNaO4", apps: ["Flavor Enhancer", "Seasoning", "Savory Foods", "Snacks"], desc: "A umami flavor enhancer that intensifies savory taste profiles in prepared foods, seasonings, and snack products. Widely approved by global food safety authorities.", purity: "99%", packaging: "25kg Bags", appearance: "White crystalline powder" },
  { name: "Gellan Gum", slug: "gellan-gum", cas: "71010-52-1", category: "food-feed-additives", image: "/images/food-feed/gellan-gum.webp", formula: "Polysaccharide", apps: ["Gelling Agent", "Beverages", "Desserts", "Plant-Based Foods"], desc: "A microbial polysaccharide providing clean gel textures at low concentrations. Ideal for plant-based dairy alternatives, desserts, and suspension beverages.", purity: "Food Grade", packaging: "25kg Bags", appearance: "Off-white powder" },
  { name: "Xylitol", slug: "xylitol", cas: "87-99-0", category: "food-feed-additives", image: "/images/food-feed/xylitol.webp", formula: "C5H12O5", apps: ["Sugar Substitute", "Dental Care", "Diabetic Foods", "Confectionery"], desc: "A natural sugar alcohol with 40% fewer calories than sucrose. Used in sugar-free gum, dental products, and diabetic-friendly foods for its tooth-friendly properties.", purity: "99%", packaging: "25kg Bags", appearance: "White crystalline" },
  { name: "Sodium Bicarbonate", slug: "sodium-bicarbonate", cas: "144-55-8", category: "food-feed-additives", image: "/images/food-feed/sodium-bicarbonate.webp", formula: "NaHCO3", apps: ["Leavening Agent", "Antacid", "Cleaning Agent", "Fire Extinguishers"], desc: "Baking soda — a safe and versatile compound used in food leavening, pharmaceutical antacids, cleaning formulations, and pH buffering applications.", purity: "99.5%", packaging: "25kg Bags", appearance: "White crystalline powder" },
  { name: "Acetic Acid", slug: "acetic-acid", cas: "64-19-7", category: "food-feed-additives", image: "/images/food-feed/acetic-acid.webp", formula: "CH3COOH", apps: ["Vinegar Production", "Food Preservative", "Chemical Synthesis", "Textile Dyeing"], desc: "The active component of vinegar, used as an acidulant and preservative in food processing. Also an important industrial solvent and chemical intermediate.", purity: "99.5%", packaging: "Drums, IBC", appearance: "Clear liquid, pungent odor" },
  { name: "Phosphoric Acid", slug: "phosphoric-acid", cas: "7664-38-2", category: "food-feed-additives", image: "/images/food-feed/phosphoric-acid.webp", formula: "H3PO4", apps: ["Soft Drinks", "Rust Removal", "Fertilizer Production", "Dental Cements"], desc: "A mineral acid used to add tartness to cola beverages, as a rust converter in metal treatment, and as a key raw material in phosphate fertilizer production.", purity: "85%", packaging: "Drums, IBC", appearance: "Clear viscous liquid" },
  { name: "Propionic Acid", slug: "propionic-acid", cas: "79-09-4", category: "food-feed-additives", image: "/images/food-feed/propionic-acid.webp", formula: "C3H6O2", apps: ["Grain Preservation", "Animal Feed", "Bread Mold Inhibitor", "Herbicide Intermediate"], desc: "A naturally occurring carboxylic acid used to prevent mold growth in animal feed, grain storage, and baked goods. An effective and safe preservation solution.", purity: "99.5%", packaging: "Drums, IBC", appearance: "Clear oily liquid" },
  { name: "Fumaric Acid", slug: "fumaric-acid", cas: "110-17-8", category: "food-feed-additives", image: "/images/food-feed/fumaric-acid.jpg", formula: "C4H4O4", apps: ["Acidulant", "Tortilla Production", "Resin Manufacturing", "Animal Feed"], desc: "A food-grade acidulant providing tartness and acting as a preservative. Valued in tortilla production and as a cost-effective alternative to citric acid.", purity: "99.5%", packaging: "25kg Bags", appearance: "White crystalline powder" },
  { name: "Mycotoxin Binder", slug: "mycotoxin-binder", cas: "Mixed", category: "food-feed-additives", image: "/images/food-feed/mycotoxin-binder.jpg", formula: "Complex", apps: ["Animal Feed", "Livestock Health", "Poultry Nutrition", "Aquaculture"], desc: "A specialized feed additive that binds and neutralizes mycotoxins in animal feed, protecting livestock health and maintaining optimal growth performance.", purity: "Feed Grade", packaging: "25kg Bags", appearance: "Fine powder" },
  { name: "Calcium Carbonate", slug: "calcium-carbonate", cas: "471-34-1", category: "food-feed-additives", image: "/images/food-feed/calcium-carbonate.webp", formula: "CaCO3", apps: ["Calcium Supplement", "Antacid", "Paper Filler", "Construction"], desc: "A mineral compound used as a dietary calcium source, paper filler and coating, construction material, and pH buffer in water treatment.", purity: "98%", packaging: "25kg Bags, Bulk", appearance: "White powder" },

  // WATER TREATMENT
  { name: "Calcium Hypochlorite", slug: "calcium-hypochlorite", cas: "7778-54-3", category: "water-treatment", image: "/images/water-treatment/calcium-hypochlorite.jpg", formula: "Ca(ClO)2", apps: ["Pool Disinfection", "Drinking Water", "Wastewater Treatment", "Sanitation"], desc: "A powerful oxidizing disinfectant for water purification, swimming pool sanitation, and municipal wastewater treatment. Provides stable available chlorine content.", purity: "65-70% AvCl", packaging: "45kg Drums", appearance: "White granules/tablets" },
  { name: "Hydrogen Peroxide", slug: "hydrogen-peroxide", cas: "7722-84-1", category: "water-treatment", image: "/images/water-treatment/hydrogen-peroxide.webp", formula: "H2O2", apps: ["Water Disinfection", "Bleaching", "Chemical Synthesis", "Environmental Remediation"], desc: "An environmentally friendly oxidizer that decomposes into water and oxygen. Used for water treatment, pulp bleaching, and as a green chemical oxidant.", purity: "35-50%", packaging: "Drums, IBC", appearance: "Clear colorless liquid" },
  { name: "Aluminum Sulfate", slug: "aluminum-sulfate", cas: "10043-01-3", category: "water-treatment", image: "/images/water-treatment/aluminum-sulfate.jpg", formula: "Al2(SO4)3", apps: ["Water Coagulant", "Paper Sizing", "pH Adjustment", "Soil Amendment"], desc: "The most widely used coagulant in municipal and industrial water treatment, effectively removing turbidity, color, and organic matter from raw water sources.", purity: "17% Al2O3", packaging: "25kg Bags, Bulk", appearance: "White/cream granules" },
  { name: "Sodium Molybdate", slug: "sodium-molybdate", cas: "7631-95-0", category: "water-treatment", image: "/images/water-treatment/sodium-molybdate.jpg", formula: "Na2MoO4", apps: ["Corrosion Inhibitor", "Cooling Systems", "Micronutrient", "Metal Finishing"], desc: "A non-toxic corrosion inhibitor for closed cooling water systems and boiler water treatment. Also used as a molybdenum micronutrient in agriculture.", purity: "99%", packaging: "25kg Bags", appearance: "White crystalline powder" },
  { name: "Ferric Chloride", slug: "ferric-chloride", cas: "7705-08-0", category: "water-treatment", image: "/images/water-treatment/calcium-chloride.jpg", formula: "FeCl3", apps: ["Water Coagulant", "Sewage Treatment", "PCB Etching", "Pigment Manufacturing"], desc: "A highly effective flocculant and coagulant for water and wastewater treatment, providing superior turbidity removal and phosphorus precipitation capabilities.", purity: "40-42%", packaging: "Drums, IBC", appearance: "Dark brown liquid" },
  { name: "Sodium Nitrite", slug: "sodium-nitrite", cas: "7632-00-0", category: "water-treatment", image: "/images/food-feed/sodium-nitrite.webp", formula: "NaNO2", apps: ["Corrosion Inhibitor", "Meat Curing", "Dye Manufacturing", "Rubber Processing"], desc: "A versatile inorganic salt used as an industrial corrosion inhibitor, meat curing agent (E250), and chemical intermediate in dye and pharmaceutical synthesis.", purity: "99%", packaging: "25kg Bags", appearance: "White/light yellow granules" },

  // MINING
  { name: "Sodium Cyanide", slug: "sodium-cyanide", cas: "143-33-9", category: "mining-chemicals", image: "/images/mining/sodium-ethyl-xanthate.webp", formula: "NaCN", apps: ["Gold Extraction", "Silver Extraction", "Electroplating", "Chemical Synthesis"], desc: "The primary reagent in gold and silver extraction through cyanidation. Supplied under strict safety protocols and regulatory compliance for mining operations worldwide.", purity: "98%", packaging: "Specialized containers", appearance: "White briquettes" },
  { name: "Sodium Ethyl Xanthate", slug: "sodium-ethyl-xanthate", cas: "140-90-9", category: "mining-chemicals", image: "/images/mining/sodium-ethyl-xanthate-a2s.png", formula: "C2H5OCS2Na", apps: ["Flotation Collector", "Copper Mining", "Zinc Mining", "Lead Mining"], desc: "A selective flotation collector used in the froth flotation separation of sulfide minerals, particularly effective for copper, zinc, lead, and nickel recovery.", purity: "90%", packaging: "25kg Drums", appearance: "Yellow/light green pellets" },
  { name: "Sodium Iso Propyl Xanthate", slug: "sodium-iso-propyl-xanthate", cas: "140-93-2", category: "mining-chemicals", image: "/images/mining/sodium-ethyl-xanthate.webp", formula: "C3H7OCS2Na", apps: ["Flotation Collector", "Copper Sulfide", "Gold Mining", "Mineral Processing"], desc: "A stronger xanthate collector than SEX, offering enhanced selectivity for sulfide mineral flotation in copper, gold, and polymetallic ore beneficiation.", purity: "90%", packaging: "25kg Drums", appearance: "Yellow pellets" },
  { name: "Activated Carbon", slug: "activated-carbon", cas: "7440-44-0", category: "mining-chemicals", image: "/images/mining/activated-carbon.jpg", formula: "C", apps: ["Gold Recovery", "Water Purification", "Air Filtration", "Chemical Purification"], desc: "High-porosity carbon with exceptional adsorption capacity, critical for gold recovery (CIP/CIL), water purification, air treatment, and chemical decolorization processes.", purity: "Iodine 900-1100 mg/g", packaging: "25kg Bags", appearance: "Black granules/powder" },
  { name: "Soda Ash Dense", slug: "soda-ash-dense", cas: "497-19-8", category: "mining-chemicals", image: "/images/mining/soda-ash-dense.png", formula: "Na2CO3", apps: ["Glass Making", "pH Regulation", "Detergents", "Metallurgy"], desc: "Sodium carbonate dense grade, essential in glass manufacturing, metallurgical fluxing, detergent production, and pH adjustment in water and mining processes.", purity: "99.2%", packaging: "50kg Bags, Bulk", appearance: "White powder" },
  { name: "Methyl Isobutyl Carbinol", slug: "methyl-isobutyl-carbinol", cas: "108-11-2", category: "mining-chemicals", image: "/images/mining/methyl-isobutyl-carbinol.jpg", formula: "C6H14O", apps: ["Frother", "Mineral Flotation", "Solvent", "Coatings"], desc: "The most widely used frother in mineral flotation processes, producing stable and controlled froth for efficient separation of valuable minerals from gangue.", purity: "99%", packaging: "Drums, IBC", appearance: "Clear colorless liquid" },
  { name: "Sulfamic Acid", slug: "sulfamic-acid", cas: "5329-14-6", category: "mining-chemicals", image: "/images/mining/sulfamic-acid.jpg", formula: "H3NO3S", apps: ["Descaling", "Metal Cleaning", "pH Control", "Electroplating"], desc: "A strong inorganic acid used for industrial cleaning, descaling of heat exchangers and boilers, and as a catalyst in various chemical processes.", purity: "99.5%", packaging: "25kg Bags", appearance: "White crystalline powder" },

  // PHARMA
  { name: "Phenol", slug: "phenol", cas: "108-95-2", category: "pharma-chemicals", image: "/images/pharma/phenol.jpg", formula: "C6H5OH", apps: ["BPA Production", "Resins", "Disinfectant", "Pharmaceutical Intermediate"], desc: "A fundamental aromatic compound used in the production of bisphenol-A, phenolic resins, caprolactam, and as a precursor for numerous pharmaceutical intermediates.", purity: "99%", packaging: "Drums, IBC", appearance: "White crystalline solid" },
  { name: "Ethanol", slug: "ethanol", cas: "64-17-5", category: "pharma-chemicals", image: "/images/pharma/ethanol.webp", formula: "C2H5OH", apps: ["Pharmaceutical Solvent", "Disinfectant", "Fuel Additive", "Beverage Production"], desc: "High-purity ethyl alcohol for pharmaceutical formulations, laboratory use, disinfection products, and as a biofuel component. Available in various grades and concentrations.", purity: "96-99.9%", packaging: "Drums, IBC, Tanker", appearance: "Clear colorless liquid" },
  { name: "Folic Acid", slug: "folic-acid", cas: "59-30-3", category: "pharma-chemicals", image: "/images/pharma/folic-acid.webp", formula: "C19H19N7O6", apps: ["Vitamin B9 Supplement", "Prenatal Nutrition", "Food Fortification", "Animal Feed"], desc: "Vitamin B9, essential for cell division and DNA synthesis. Widely used in pharmaceutical supplements, prenatal vitamins, and food fortification programs.", purity: "97%", packaging: "25kg Drums", appearance: "Yellow-orange powder" },
  { name: "Glycolic Acid", slug: "glycolic-acid", cas: "79-14-1", category: "pharma-chemicals", image: "/images/pharma/glycolic-acid.webp", formula: "C2H4O3", apps: ["Skin Care", "Chemical Peels", "Cleaning Agents", "Textile Processing"], desc: "An alpha hydroxy acid (AHA) used in dermatological products for exfoliation, anti-aging treatments, and as an effective industrial cleaning and descaling agent.", purity: "70%", packaging: "Drums, IBC", appearance: "Clear colorless liquid" },
  { name: "Sodium Starch Glycolate", slug: "sodium-starch-glycolate", cas: "9063-38-1", category: "pharma-chemicals", image: "/images/pharma/sodium-starch-glycolate.jpg", formula: "Modified starch", apps: ["Tablet Disintegrant", "Pharmaceutical Excipient", "Capsule Formulation"], desc: "A super-disintegrant used in pharmaceutical tablet and capsule formulations to promote rapid disintegration and drug release upon ingestion.", purity: "USP/EP Grade", packaging: "25kg Drums", appearance: "White powder" },

  // INORGANIC
  { name: "Mercury", slug: "mercury", cas: "7439-97-6", category: "inorganic-chemicals", image: "/images/inorganic/mercury.webp", formula: "Hg", apps: ["Scientific Instruments", "Dental Amalgam", "Chlor-alkali Process", "Gold Mining"], desc: "Liquid metal supplied under strict regulatory compliance for authorized industrial and scientific applications. Subject to Minamata Convention controls.", purity: "99.99%", packaging: "Flask (34.5kg)", appearance: "Silver liquid metal" },
  { name: "Lead Nitrate", slug: "lead-nitrate", cas: "10099-74-8", category: "inorganic-chemicals", image: "/images/inorganic/lead-nitrate.webp", formula: "Pb(NO3)2", apps: ["Gold Cyanidation", "Pigment Manufacturing", "Explosive Detonators", "Analytical Reagent"], desc: "An oxidizing agent used as an accelerator in gold cyanidation processes and in the production of specialty pigments and analytical chemistry applications.", purity: "99%", packaging: "25kg Bags", appearance: "White crystalline powder" },
  { name: "Cobalt Carbonate", slug: "cobalt-carbonate", cas: "513-79-1", category: "inorganic-chemicals", image: "/images/inorganic/cobalt-carbonate.webp", formula: "CoCO3", apps: ["Ceramics Colorant", "Battery Materials", "Catalyst Production", "Animal Feed"], desc: "A cobalt salt used to produce vivid blue colorants in ceramics and glass, as a precursor for battery cathode materials, and in catalyst manufacturing.", purity: "46% Co", packaging: "25kg Bags", appearance: "Pink/red powder" },
  { name: "Copper Oxide", slug: "copper-oxide", cas: "1317-38-0", category: "inorganic-chemicals", image: "/images/inorganic/copper-oxide.webp", formula: "CuO", apps: ["Ceramics", "Antifouling Paints", "Catalysts", "Animal Feed Supplement"], desc: "A black copper compound used as a colorant in ceramics, an active ingredient in antifouling marine paints, and a copper supplement in animal nutrition.", purity: "98%", packaging: "25kg Bags", appearance: "Black powder" },
  { name: "Nickel Oxide", slug: "nickel-oxide", cas: "1313-99-1", category: "inorganic-chemicals", image: "/images/inorganic/nickel-oxide.webp", formula: "NiO", apps: ["Battery Materials", "Ceramics", "Catalyst Production", "Specialty Alloys"], desc: "A green nickel compound used in nickel-cadmium and nickel-metal hydride batteries, ceramic pigments, and as a precursor for nickel-based catalysts.", purity: "78% Ni", packaging: "25kg Bags", appearance: "Green/black powder" },

  // SOLVENTS
  { name: "Butanol", slug: "butanol", cas: "71-36-3", category: "solvents-glycols", image: "/images/solvents/butanol.webp", formula: "C4H9OH", apps: ["Coatings", "Plasticizers", "Hydraulic Fluids", "Chemical Intermediate"], desc: "A versatile primary alcohol used as a solvent in coatings and lacquers, as a chemical intermediate for butyl acrylate, and in plasticizer manufacturing.", purity: "99.5%", packaging: "Drums, IBC", appearance: "Clear colorless liquid" },
  { name: "Propanone (Acetone)", slug: "propanone", cas: "67-64-1", category: "solvents-glycols", image: "/images/solvents/propanone.webp", formula: "C3H6O", apps: ["Solvent", "Nail Polish Remover", "Chemical Intermediate", "Cleaning Agent"], desc: "A fast-evaporating ketone solvent widely used in paints, coatings, adhesives, and as a chemical precursor for methyl methacrylate and bisphenol-A production.", purity: "99.5%", packaging: "Drums, IBC", appearance: "Clear colorless liquid" },
  { name: "Diethanolamine", slug: "diethanolamine", cas: "111-42-2", category: "solvents-glycols", image: "/images/solvents/diethanolamine.webp", formula: "C4H11NO2", apps: ["Gas Scrubbing", "Metalworking Fluids", "Personal Care", "Herbicide Production"], desc: "An amino alcohol used for acid gas removal in natural gas processing, as an emulsifier in metalworking fluids, and as an intermediate in herbicide synthesis.", purity: "99%", packaging: "Drums, IBC", appearance: "Clear viscous liquid" },
  { name: "Dipropylene Glycol", slug: "dipropylene-glycol", cas: "25265-71-8", category: "solvents-glycols", image: "/images/solvents/dipropylene-glycol.webp", formula: "C6H14O3", apps: ["Fragrance Carrier", "Plasticizers", "Polyester Resins", "Coatings"], desc: "A low-toxicity glycol ether used as a fragrance carrier in personal care, a reactant in polyester resins, and a coupling solvent in coating formulations.", purity: "99%", packaging: "Drums, IBC", appearance: "Clear colorless liquid" },
  { name: "Monoethylene Glycol", slug: "monoethylene-glycol-solvent", cas: "107-21-1", category: "solvents-glycols", image: "/images/solvents/monoethylene-glycol.webp", formula: "C2H6O2", apps: ["Antifreeze", "Polyester Production", "Deicing", "Heat Transfer"], desc: "An essential glycol used as the base for automotive antifreeze, in polyester fiber and PET bottle production, and as a deicing fluid for aircraft.", purity: "99.5%", packaging: "Drums, IBC, Flexitanks", appearance: "Clear colorless liquid" },

  // PAPER/PULP/TEXTILE
  { name: "Methyl Cellulose", slug: "methyl-cellulose", cas: "9004-67-5", category: "paper-pulp-textile", image: "/images/food-feed/methyl-cellulose.webp", formula: "Modified cellulose", apps: ["Wallpaper Adhesive", "Tile Adhesive", "Pharmaceutical Binder", "Food Thickener"], desc: "A cellulose ether providing thickening, binding, and water retention properties for construction adhesives, pharmaceutical coatings, and food applications.", purity: "Various grades", packaging: "25kg Bags", appearance: "White fibrous powder" },
  { name: "Potato Starch", slug: "potato-starch", cas: "9005-25-8", category: "paper-pulp-textile", image: "/images/food-feed/potato-starch.webp", formula: "Starch", apps: ["Paper Coating", "Textile Sizing", "Food Thickener", "Biodegradable Packaging"], desc: "A natural starch used in paper surface sizing and coating, textile warp sizing, food thickening, and as a base material for biodegradable packaging films.", purity: "Food/Industrial Grade", packaging: "25kg Bags", appearance: "White fine powder" },
  { name: "Gum Arabic", slug: "gum-arabic", cas: "9000-01-5", category: "paper-pulp-textile", image: "/images/food-feed/gum-arabic.webp", formula: "Polysaccharide", apps: ["Printing Inks", "Confectionery", "Beverages", "Pharmaceutical Coating"], desc: "A natural tree exudate gum providing emulsification, film-forming, and stabilizing properties for printing, confectionery, beverages, and pharmaceutical coatings.", purity: "Food Grade", packaging: "25kg Bags", appearance: "Amber powder/pieces" },

  // RUBBER/LEATHER/SPECIALTY
  { name: "Oleic Acid", slug: "oleic-acid", cas: "112-80-1", category: "rubber-leather-specialty", image: "/images/rubber-specialty/oleic-acid.webp", formula: "C18H34O2", apps: ["Soap Manufacturing", "Lubricants", "Textile Processing", "Rubber Processing"], desc: "A monounsaturated fatty acid used in soap manufacturing, as a lubricant additive, rubber processing aid, and emollient in personal care formulations.", purity: "80%", packaging: "Drums, IBC", appearance: "Pale yellow oily liquid" },
  { name: "Fatty Acid", slug: "fatty-acid", cas: "Mixed", category: "rubber-leather-specialty", image: "/images/rubber-specialty/fatty-acid.webp", formula: "Various", apps: ["Rubber Activator", "Candle Making", "Metalworking", "PVC Stabilizer"], desc: "Industrial-grade fatty acids derived from vegetable oils, used as rubber vulcanization activators, metalworking lubricants, and PVC heat stabilizer intermediates.", purity: "Various grades", packaging: "Drums, Flexitanks", appearance: "White/yellow solid" },
  { name: "Palmitic Acid", slug: "palmitic-acid", cas: "57-10-3", category: "rubber-leather-specialty", image: "/images/rubber-specialty/palmitic-acid.webp", formula: "C16H32O2", apps: ["Soap Base", "Cosmetics", "Food Emulsifier", "Rubber Processing"], desc: "A saturated fatty acid used as a primary raw material in soap production, cosmetic emulsifiers, food-grade release agents, and rubber processing chemicals.", purity: "95%", packaging: "25kg Bags", appearance: "White crystalline flakes" },
  { name: "Glutaraldehyde", slug: "glutaraldehyde", cas: "111-30-8", category: "rubber-leather-specialty", image: "/images/rubber-specialty/glutaraldehyde.webp", formula: "C5H8O2", apps: ["Leather Tanning", "Disinfectant", "Oil Field Biocide", "Tissue Fixative"], desc: "A dialdehyde biocide used in leather tanning, hospital-grade disinfection, oil field water treatment, and biological tissue fixation for microscopy.", purity: "25-50%", packaging: "Drums, IBC", appearance: "Clear yellowish liquid" },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter((p) => p.category === categoryId);
}

export function getCategoryById(id: string): Category | undefined {
  return categories.find((c) => c.id === id);
}
